import "./scss/app.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "simplebar-react/dist/simplebar.min.css";
import { QueryProvider } from "@/utils/QueryClientProvider";
import { SnackbarProvider } from "@/utils/QueryProvider";
import { ReduxProvider } from "@/utils/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SnackbarProvider>
          <QueryProvider>
            <ReduxProvider>{children}</ReduxProvider>
          </QueryProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
