import { AdminLayout } from "@/components/layouts/admin/layout";
import { QueryProvider } from "@/utils/QueryClientProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

          <AdminLayout>{children}</AdminLayout>

      </body>
    </html>
  );
}
